### ISSUE TITLE
Ttoggle raise an error: Failed to connect to bus: No such file or directory when using user mode trusted units

### ISSUE THREAD

**Issue by dummys** [pigmonkey/nmtrust#13]
Hey,
Thanks for spark and all the little gem you developed so far, really appreciate to use it.
I'm using syncthing to synchronise my stuff and my trusted_units looks like this:
`syncthing.service,user:myuser`
When using `sudo ttoggle` I get an error:
`Failed to connect to bus: No such file or directory`
I have other trusted units which are not user, they are working correctly.
How I can debug this problem ?
If I use `journalctl -fl` I see that a command is run:
```
fév 05 07:57:21  sudo[144802]:     myuser : TTY=pts/2 ; PWD=/home/myuser ; USER=root ; COMMAND=/usr/bin/ttoggle
fév 05 07:57:21  sudo[144802]: pam_unix(sudo:session): session opened for user root(uid=0) by myuser(uid=1337)
fév 05 07:57:21  sudo[144863]:     root : TTY=pts/4 ; PWD=/home/myuser ; USER=myuser ; COMMAND=/usr/bin/bash -c 'export XDG_RUNTIME_DIR=/run/user/1000; systemctl stop --user syncthing.service'
```
The command looks good, but syncthing is not stopped.
If I copy/past the same command in my shell, syncthing get stopped.

EDIT: I understand why, my uid is 1337 and not 1000, that's why it is failing in the `ttoggle` script
dirty fix would be in file ttoggle
https://github.com/pigmonkey/nmtrust/blob/b1a43f43da29e38bf62d4d298127299a62258417/ttoggle#L59C9-L59C87
`sudo -u "$unit_user" bash -c "export XDG_RUNTIME_DIR=/run/user/$(sudo -u "$unit_user" bash -c "id -u"); $command"`

I'm also wondering if we should modify in spark: 

https://github.com/pigmonkey/spark/blob/1a485d95bab2842381ba5a26bcd3e0184fdffb6b/roles/base/tasks/user.yml#L5

To use also `gid: "{{ user.uid }}"` in case the user want to change the default uid and that we match the gid as well.

Another issue I encountered, is that using nmtrust with NetworkManager raise an error in the journalctl log:
`tput: No value for $TERM and no -T specified` 
https://github.com/pigmonkey/nmtrust/blob/b1a43f43da29e38bf62d4d298127299a62258417/nmtrust#L9
This is because the tput want a $TERM. I wrote a simple workarround using:

`if tty -s; then` before the whole functions, which will run only if we are in a terminal

**Comment by pigmonkey** [comment]
Replacing the hardcoded `/run/user/1000` in ttoggle makes sense. Probably better to just get it with `id -u "$unit_user"` though. There's no reason for another `sudo` call there.

I'd be fine with setting the group ID in spark, but I'd prefer to actually define a new `user.gid` variable for it, rather than assume the user always wants it to be the same as the user ID.

I don't see any errors in my NetworkManager log from that `tput`. It should be redirecting all output to `/dev/null` anyways. But I'd be ok with also checking for a non-zero `$TERM` on that line. I think that would be a little clearer than calling `tty`, even if both have the same effect.

**Comment by dummys** [comment]
excellent thanks for fix.
